# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dev-moviesappsep6

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://sepmoviesregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_31e147b6b54d448e836e6e0f73016ba6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4ed0701ac7ca4ca6a56e8a01119bcbe3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sepmoviesregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_31e147b6b54d448e836e6e0f73016ba6 }}/moviesapp-dev:${{ github.sha }}
        file: ./Dockerfile-dev

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dev-moviesappsep6'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4d8d1e5f936048b1b90d4f6ab9be4815 }}
        images: 'sepmoviesregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_31e147b6b54d448e836e6e0f73016ba6 }}/moviesapp-dev:${{ github.sha }}'